exp_name: CCR5
seed: 2023
epochs: 15
distributed: true
lr: 2e-4
lr_min: 2e-5
weight_decay: 0.0
resume_state: null
save_dir: work_dir
eval_interval: 1

network:
  name: networks.SPF.SPF
  params:
    gmsf_pretrained: GMSF2D/pretrained/VESICLE7low135_64_4.pth
    syn_pretrained: pretrained/AMT/syn.pth
data:
  train: 
    name: datasets.particle_datasets.ParticleDatasetReal
    params: 
      mode: train
      dataset_name: CCR5
      data_root: data/REAL # change it to your own data_root 
      npoints: 75
  val:
    name: datasets.particle_datasets.ParticleDatasetReal
    params: 
      mode: test
      dataset_name: CCR5
      data_root: data/REAL # change it to your own data_root 
      npoints: 75
  train_loader:
    batch_size: 1
    num_workers: 1
  val_loader:
    batch_size: 1
    num_workers: 1

logger:
  use_wandb: true  
  resume_id: null

losses:
  - {
    name: losses.loss.CharbonnierLoss,
    nickname: l_rec,
    params: {
      loss_weight: 1.0,
      keys: [imgt_pred, imgt]
    }
  }
  - {
    name: losses.loss.TernaryLoss,
    nickname: l_ter,
    params: {
      loss_weight: 1.0,
      keys: [imgt_pred, imgt]
    }
  }
  - {
    name: losses.loss.MultipleFlowLoss,
    nickname: l_flo,
    params: {
      loss_weight: 0.002,
      keys: [flow0_pred, flow1_pred, flow]
    }
  }